service:
  name: telegram-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DEBUG: ${env:DEBUG}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    WIT_TOKEN: ${env:WIT_TOKEN}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    BUCKET: ${env:BUCKET}
    TELEGRAM_HANDLE: ${env:TELEGRAM_HANDLE}
    APIFLASH_TOKEN: ${env:APIFLASH_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:BUCKET}/*"
functions:
  receive-updates:
    handler: handler.handler
    events:
      - http:
          method: post
          path: telegram-hook
          cors: true

resources:
  Resources:
    PetsTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
