service:
  name: telegram-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    DEBUG: "*"

functions:
  receive-updates:
    handler: handler.handler
    events:
      - http:
          method: post
          path: telegram-hook
          cors: true
